# Generated by Django 5.0.2 on 2024-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('Curd', 'CR'), ('ML', 'Milk'), ('Lassi', 'LS'), ('MilkShake', 'MS'), ('PR', 'Paneer'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('Icebars', 'IC')], max_length=9)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
