# Generated by Django 5.0.2 on 2024-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('Milk', 'ML'), ('LS', 'Lassi'), ('MS', 'MilkShake'), ('Paneer', 'PR'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('Icebars', 'IC')], max_length=9),
        ),
    ]
