# Generated by Django 5.0.2 on 2024-07-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0003_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MilkShake', 'MS'), ('Paneer', 'PR'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('IC', 'Icebars')], max_length=9),
        ),
    ]
