# Generated by Django 5.0.2 on 2024-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0005_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'MilkShake'), ('PR', 'Paneer'), ('Ghee', 'GH'), ('CH', 'Cheese'), ('Icebars', 'IC')], max_length=9),
        ),
    ]
