# Generated by Django 5.0.2 on 2024-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('Milk', 'ML'), ('Lassi', 'LS'), ('MilkShake', 'MS'), ('PR', 'Paneer'), ('Ghee', 'GH'), ('Cheese', 'CH'), ('IC', 'Icebars'), ('kulfi', 'KF')], max_length=9),
        ),
    ]
