# Generated by Django 5.0.2 on 2024-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('Milk', 'ML'), ('LS', 'Lassi'), ('MS', 'MilkShake'), ('Paneer', 'PR'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('Icebars', 'IC'), ('KF', 'kulfi')], max_length=9),
        ),
    ]
