# Generated by Django 5.0.2 on 2024-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0010_alter_product_category_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paytm_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paytm_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paytm_payment_status',
            new_name='razorpay_payment_status',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('Milk', 'ML'), ('LS', 'Lassi'), ('MilkShake', 'MS'), ('PR', 'Paneer'), ('GH', 'Ghee'), ('Cheese', 'CH'), ('IC', 'Icebars'), ('kulfi', 'KF')], max_length=9),
        ),
    ]
