# Generated by Django 5.0.2 on 2024-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0011_rename_paytm_order_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('Lassi', 'LS'), ('MS', 'MilkShake'), ('PR', 'Paneer'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('IC', 'Icebars'), ('kulfi', 'KF')], max_length=9),
        ),
    ]
