# Generated by Django 5.0.2 on 2024-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('ML', 'Milk'), ('Lassi', 'LS'), ('MilkShake', 'MS'), ('Paneer', 'PR'), ('Ghee', 'GH'), ('Cheese', 'CH'), ('IC', 'Icebars'), ('KF', 'kulfi')], max_length=9),
        ),
    ]
