# Generated by Django 5.0.2 on 2024-08-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0014_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Curd', 'CR'), ('Milk', 'ML'), ('LS', 'Lassi'), ('MS', 'MilkShake'), ('Paneer', 'PR'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('IC', 'Icebars'), ('kulfi', 'KF')], max_length=9),
        ),
    ]
