# Generated by Django 5.0.2 on 2024-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('Milk', 'ML'), ('LS', 'Lassi'), ('MilkShake', 'MS'), ('PR', 'Paneer'), ('Ghee', 'GH'), ('CH', 'Cheese'), ('IC', 'Icebars'), ('kulfi', 'KF')], max_length=9),
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
