# Generated by Django 5.0.2 on 2024-08-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkMagic', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('Milk', 'ML'), ('Lassi', 'LS'), ('MilkShake', 'MS'), ('Paneer', 'PR'), ('GH', 'Ghee'), ('Cheese', 'CH'), ('Icebars', 'IC'), ('KF', 'kulfi')], max_length=9),
        ),
    ]
